### ISSUE TITLE
Getting Error while training the neural net !!!

### ISSUE THREAD

**Issue by sahil210695** [trailbehind/DeepOSM#72] opened 2017-01-19 05:10 UTC
1. Installed the Docker
2. make dev command executed successfully.
3. after that when I'm executing the python bin/create_training_data.py I'm getting some errors like : 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd ls --recursive --skip-existing s3://aws-naip/in/2014/1m/rgbir/ --requester-pays
Problem: gaierror: [Errno -2] Name or service not known
S3cmd:   1.6.0
python:   2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
environment LANG=None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2805, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2713, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 120, in cmd_ls
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 153, in subcmd_bucket_list
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 293, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 320, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 339, in bucket_list_noparse
    response = self.send_request(request)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 1061, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "build/bdist.linux-x86_64/egg/S3/ConnMan.py", line 179, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 1216, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DOWNLOADING 1 PBFs...
downloads took 3.7s
EXTRACTED WAYS with locations from pbf file /DeepOSM/data/openstreetmap/delaware-latest.osm.pbf, took 7.1s

--------------------------------
please help
Using macOS Sierra

**Comment by wmaiouiru** [comment] 2017-01-23 05:03
@sahil210695

I had some other problem with s3cmd and I was able to resolve the problem by reinstalling it and re-configuring it. I am also on macOS Sierra. 
http://askubuntu.com/questions/38692/how-does-one-remove-applications-installed-through-python-setup-py-install

**Comment by andrewljohnson** [comment] 2017-01-30 05:42
Not sure what the issue is here, but it seemed to be related to s3cmd configuration, closing for now.

**Closed as completed by andrewljohnson** 2017-01-30 05:42 UTC

**Comment by sahil210695** [comment] 2017-02-10 04:13
@andrewljohnson I'm not able to download the images from the AWS and I got the third party site for doing the same but I am not getting how to put those images and in which directory.
link of the side which is providing the NAIP images
link: [https://f5f3hkneq5.execute-api.us-east-1.amazonaws.com/prod/de/2013/1m/rgbir](url)
please tell me how i can download the images or anyone can give me the images directory so that i can run this and have look at this how it is working !

**Comment by andrewljohnson** [comment] 2017-02-10 16:05
I'm sorry, I don't know what's going wrong for you.

**Comment by sahil210695** [comment] 2017-02-11 13:12
@andrewljohnson can you provide me the image directory because I'm not able to download the images for the Delaware thru AWS getting the error that I mentioned in the first post.
So that at least I can check how it is working.

**Comment by andrewljohnson** [comment] 2017-02-11 21:10
Sorry, I can't help.

**Comment by sahil210695** [comment] 2017-02-15 09:20
Getthing this while running the **train_neural_net.py**

WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
